// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3N8ONaTDF8G-B1SthI3aCV-vRR_5H3q4',
    appId: '1:114582733651:web:07c3b15b75eee36a4a17a6',
    messagingSenderId: '114582733651',
    projectId: 'fireflutternew',
    authDomain: 'fireflutternew.firebaseapp.com',
    databaseURL: 'https://fireflutternew.firebaseio.com',
    storageBucket: 'fireflutternew.appspot.com',
    measurementId: 'G-80B9X9KDQW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATj_WFIWozgLi4fMU7qw-z4wx4QLcE3Rc',
    appId: '1:114582733651:android:0677ba4b345eb36d4a17a6',
    messagingSenderId: '114582733651',
    projectId: 'fireflutternew',
    databaseURL: 'https://fireflutternew.firebaseio.com',
    storageBucket: 'fireflutternew.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCH_NggxKyHfp_FgLkPTEMCDoyyzwOqrQU',
    appId: '1:114582733651:ios:3f37c1c43fdc9a634a17a6',
    messagingSenderId: '114582733651',
    projectId: 'fireflutternew',
    databaseURL: 'https://fireflutternew.firebaseio.com',
    storageBucket: 'fireflutternew.appspot.com',
    iosBundleId: 'com.example.tratcncr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCH_NggxKyHfp_FgLkPTEMCDoyyzwOqrQU',
    appId: '1:114582733651:ios:3f37c1c43fdc9a634a17a6',
    messagingSenderId: '114582733651',
    projectId: 'fireflutternew',
    databaseURL: 'https://fireflutternew.firebaseio.com',
    storageBucket: 'fireflutternew.appspot.com',
    iosBundleId: 'com.example.tratcncr',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3N8ONaTDF8G-B1SthI3aCV-vRR_5H3q4',
    appId: '1:114582733651:web:94bea535bbf179cf4a17a6',
    messagingSenderId: '114582733651',
    projectId: 'fireflutternew',
    authDomain: 'fireflutternew.firebaseapp.com',
    databaseURL: 'https://fireflutternew.firebaseio.com',
    storageBucket: 'fireflutternew.appspot.com',
    measurementId: 'G-C9F2FRZ6X2',
  );
}
